import type { AthletePayload } from './components/AthleteDetail.js';
import realData from './fixtures/attended-player.json' with { type: 'json' };

const real = realData as unknown as AthletePayload;

// Mariners team object reused across the Mariners fixtures. Pulled
// from the live API response shape so all fields the component
// consumes (logo URLs, ui_tint_color, primary_color) are present.
const mariners = {
  id: 136,
  league: 'mlb',
  abbreviation: 'SEA',
  location: 'Seattle',
  name: 'Mariners',
  full_name: 'Seattle Mariners',
  primary_color: '#005C5C',
  secondary_color: '#0C2C56',
  tertiary_color: null,
  ui_tint_color: '#005C5C',
  logo_url: 'https://www.mlbstatic.com/team-logos/136.svg',
  logo_dark_url:
    'https://www.mlbstatic.com/team-logos/team-cap-on-dark/136.svg',
  logo_light_url:
    'https://www.mlbstatic.com/team-logos/team-cap-on-light/136.svg',
  conference: 'AL',
  division: 'AL West',
} as unknown as AthletePayload['player']['primary_team'];

// JP Crawford — American hitter, no college (drafted out of HS in 2013).
// Bio strip exercises every field except COLLEGE so we can see the
// flex-wrap layout collapse cleanly without a trailing empty grid cell.
const jpCrawford: AthletePayload = {
  player: {
    id: 125,
    mlb_stats_id: 641487,
    full_name: 'J.P. Crawford',
    primary_position: 'SS',
    primary_number: '3',
    bats: 'L',
    throws: 'R',
    debut_date: '2017-09-05',
    birth_date: '1995-01-11',
    birth_city: 'Long Beach',
    birth_state_province: 'CA',
    birth_country: 'USA',
    height: '6\' 0"',
    weight: 202,
    college_name: null,
    awards: [{ season: '2020', id: 'ALGG', name: 'Rawlings AL Gold Glove' }],
    photo_silo: {
      cdn_url:
        'https://cdn.rewind.rest/cdn-cgi/image/width=300,height=300,fit=cover,format=auto,quality=85/attending/player_silo/125/original.png?v=1',
      url: null,
      thumbhash: 'nRiGFQJHiHZxmokJ+Gh4gHYIB4iGiId4Zw==',
      dominant_color: '#1c1e21',
      accent_color: '#deaa8a',
    },
    photo_full: {
      cdn_url:
        'https://cdn.rewind.rest/cdn-cgi/image/width=300,height=300,fit=cover,format=auto,quality=85/attending/player_full/125/original.png?v=1',
      url: null,
      thumbhash: 'ZxiKFQI36GaAh343yEeLgKQIB6iBh4lKdw==',
      dominant_color: '#eef2f8',
      accent_color: '#cf9878',
    },
    league: 'mlb',
    primary_team: mariners,
  },
  supported: true,
  season_stats: {
    season: 2026,
    fetched_at: '2026-04-29T05:57:48Z',
    cache_hit: true,
    hitter: {
      games_played: 23,
      pa: 96,
      ab: 77,
      r: 12,
      h: 14,
      doubles: 3,
      triples: 0,
      hr: 1,
      rbi: 6,
      bb: 17,
      k: 16,
      sb: 1,
      avg: '.182',
      obp: '.344',
      slg: '.260',
      ops: '.604',
    },
    pitcher: null,
  },
  career: {
    group: 'hitting',
    fetched_at: '2026-04-28T19:02:11Z',
    cache_hit: true,
    seasons: [
      {
        season: '2022',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 27,
        games_played: 145,
        pa: 603,
        ab: 518,
        r: 57,
        h: 126,
        doubles: 24,
        triples: 3,
        hr: 6,
        rbi: 42,
        bb: 68,
        k: 80,
        sb: 3,
        avg: '.243',
        obp: '.339',
        slg: '.336',
        ops: '.675',
      },
      {
        season: '2023',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 28,
        games_played: 145,
        pa: 638,
        ab: 534,
        r: 94,
        h: 142,
        doubles: 35,
        triples: 0,
        hr: 19,
        rbi: 65,
        bb: 94,
        k: 125,
        sb: 2,
        avg: '.266',
        obp: '.380',
        slg: '.438',
        ops: '.818',
      },
      {
        season: '2024',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 29,
        games_played: 105,
        pa: 451,
        ab: 392,
        r: 55,
        h: 79,
        doubles: 16,
        triples: 2,
        hr: 9,
        rbi: 37,
        bb: 52,
        k: 102,
        sb: 5,
        avg: '.202',
        obp: '.304',
        slg: '.321',
        ops: '.625',
      },
      {
        season: '2025',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 30,
        games_played: 157,
        pa: 654,
        ab: 570,
        r: 69,
        h: 151,
        doubles: 24,
        triples: 0,
        hr: 12,
        rbi: 58,
        bb: 74,
        k: 122,
        sb: 8,
        avg: '.265',
        obp: '.352',
        slg: '.370',
        ops: '.722',
      },
      {
        season: '2026',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 31,
        games_played: 22,
        pa: 91,
        ab: 73,
        r: 11,
        h: 13,
        doubles: 3,
        triples: 0,
        hr: 1,
        rbi: 6,
        bb: 16,
        k: 16,
        sb: 0,
        avg: '.178',
        obp: '.341',
        slg: '.260',
        ops: '.601',
      },
    ],
  } as unknown as AthletePayload['career'],
  splits: {
    season: 2026,
    group: 'hitting',
    fetched_at: '2026-04-29T05:57:48Z',
    cache_hit: true,
    home: {
      avg: '.278',
      obp: '.422',
      slg: '.417',
      ops: '.839',
      hr: 1,
      rbi: 6,
      ab: 36,
      h: 10,
    },
    away: {
      avg: '.098',
      obp: '.275',
      slg: '.122',
      ops: '.397',
      hr: 0,
      rbi: 0,
      ab: 41,
      h: 4,
    },
    vs_left: {
      avg: '.100',
      obp: '.333',
      slg: '.250',
      ops: '.583',
      hr: 1,
      rbi: 2,
      ab: 20,
      h: 2,
    },
    vs_right: {
      avg: '.211',
      obp: '.348',
      slg: '.263',
      ops: '.611',
      hr: 0,
      rbi: 4,
      ab: 57,
      h: 12,
    },
  } as unknown as AthletePayload['splits'],
  attended_summary: {
    games_attended: 32,
    games_with_box_score: 30,
    wins: 0,
    losses: 0,
    hitter: {
      pa: 127,
      ab: 111,
      r: 22,
      h: 37,
      doubles: 6,
      triples: 0,
      hr: 5,
      rbi: 19,
      bb: 16,
      k: 23,
      sb: 1,
      avg: '.333',
      obp: '.417',
      slg: '.523',
      ops: '.940',
    },
    pitcher: null,
  },
  attended_appearances: [
    {
      event_id: 57,
      event_date: '2026-04-19',
      title: 'Seattle Mariners vs Texas Rangers',
      is_home: true,
      batting_line: {
        ab: 3,
        r: 1,
        h: 1,
        rbi: 2,
        bb: 1,
        k: 1,
        hr: 1,
        doubles: 0,
        triples: 0,
        sb: 0,
        hbp: 0,
        pa: 4,
        total_bases: 4,
        left_on_base: 1,
        summary: '1-3 | HR, BB, K',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: ['1 HR'],
    } as unknown as AthletePayload['attended_appearances'][number],
    {
      event_id: 104,
      event_date: '2026-04-11',
      title: 'Seattle Mariners vs Houston Astros',
      is_home: true,
      batting_line: {
        ab: 3,
        r: 2,
        h: 2,
        rbi: 3,
        bb: 2,
        k: 0,
        hr: 0,
        doubles: 0,
        triples: 0,
        sb: 0,
        hbp: 0,
        pa: 5,
        total_bases: 2,
        left_on_base: 0,
        summary: '2-3 | 2 BB, 3 RBI, 2 R',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: [],
    } as unknown as AthletePayload['attended_appearances'][number],
    {
      event_id: 43,
      event_date: '2025-05-31',
      title: 'Seattle Mariners vs Minnesota Twins',
      is_home: true,
      batting_line: {
        ab: 4,
        r: 1,
        h: 3,
        rbi: 2,
        bb: 1,
        k: 1,
        hr: 1,
        doubles: 1,
        triples: 0,
        sb: 0,
        hbp: 0,
        pa: 5,
        total_bases: 7,
        left_on_base: 1,
        summary: '3-4 | HR, 2B, BB',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: ['1 HR', 'multi-hit'],
    } as unknown as AthletePayload['attended_appearances'][number],
  ],
  attended_appearance_count: 32,
};

// Julio Rodríguez — Dominican Republic, no college (international
// signing pipeline). Tests the BioStrip with the international-
// birthplace path (no state/province) AND the no-college branch,
// plus the longer awards list.
const julioRodriguez: AthletePayload = {
  player: {
    id: 143,
    mlb_stats_id: 677594,
    full_name: 'Julio Rodríguez',
    primary_position: 'CF',
    primary_number: '44',
    bats: 'R',
    throws: 'R',
    debut_date: '2022-04-08',
    birth_date: '2000-12-29',
    birth_city: 'Loma de Cabrera',
    birth_state_province: null,
    birth_country: 'Dominican Republic',
    height: '6\' 4"',
    weight: 228,
    college_name: null,
    awards: [
      { season: '2025', id: 'ALAS', name: 'AL All-Star' },
      { season: '2025', id: 'MLBAFIRST', name: 'All-MLB First Team' },
      { season: '2023', id: 'ALAS', name: 'AL All-Star' },
      { season: '2023', id: 'ALSS', name: 'AL Silver Slugger' },
      { season: '2022', id: 'ALAS', name: 'AL All-Star' },
      {
        season: '2022',
        id: 'BAMLROY',
        name: 'Baseball America Major League Rookie of the Year',
      },
      { season: '2022', id: 'ALSS', name: 'AL Silver Slugger' },
      {
        season: '2022',
        id: 'ALROY',
        name: 'Jackie Robinson AL Rookie of the Year',
      },
    ],
    photo_silo: {
      cdn_url:
        'https://cdn.rewind.rest/cdn-cgi/image/width=300,height=300,fit=cover,format=auto,quality=85/attending/player_silo/143/original.png?v=1',
      url: null,
      thumbhash: 'HkmGDQJGiHdwjHh4x2hzgDYHCIeHeHZodw==',
      dominant_color: '#a47656',
      accent_color: '#d39975',
    },
    photo_full: {
      cdn_url:
        'https://cdn.rewind.rest/cdn-cgi/image/width=300,height=300,fit=cover,format=auto,quality=85/attending/player_full/143/original.png?v=1',
      url: null,
      thumbhash: 'qCiKFQQ2uFeAen1nyEeKcKQIB6hziIlKhw==',
      dominant_color: '#ebeff7',
      accent_color: '#d39671',
    },
    league: 'mlb',
    primary_team: mariners,
  },
  supported: true,
  season_stats: {
    season: 2026,
    fetched_at: '2026-04-29T05:55:32Z',
    cache_hit: true,
    hitter: {
      games_played: 31,
      pa: 135,
      ab: 121,
      r: 14,
      h: 31,
      doubles: 6,
      triples: 0,
      hr: 2,
      rbi: 12,
      bb: 12,
      k: 30,
      sb: 3,
      avg: '.256',
      obp: '.333',
      slg: '.355',
      ops: '.688',
    },
    pitcher: null,
  },
  career: {
    group: 'hitting',
    fetched_at: '2026-04-29T05:55:32Z',
    cache_hit: true,
    seasons: [
      {
        season: '2022',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 21,
        games_played: 132,
        pa: 560,
        ab: 511,
        r: 84,
        h: 145,
        doubles: 25,
        triples: 3,
        hr: 28,
        rbi: 75,
        bb: 40,
        k: 145,
        sb: 25,
        avg: '.284',
        obp: '.345',
        slg: '.509',
        ops: '.854',
      },
      {
        season: '2023',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 22,
        games_played: 155,
        pa: 714,
        ab: 654,
        r: 102,
        h: 180,
        doubles: 37,
        triples: 2,
        hr: 32,
        rbi: 103,
        bb: 47,
        k: 175,
        sb: 37,
        avg: '.275',
        obp: '.333',
        slg: '.485',
        ops: '.818',
      },
      {
        season: '2024',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 23,
        games_played: 143,
        pa: 613,
        ab: 567,
        r: 76,
        h: 155,
        doubles: 17,
        triples: 0,
        hr: 20,
        rbi: 68,
        bb: 38,
        k: 156,
        sb: 24,
        avg: '.273',
        obp: '.325',
        slg: '.409',
        ops: '.734',
      },
      {
        season: '2025',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 24,
        games_played: 160,
        pa: 710,
        ab: 652,
        r: 106,
        h: 174,
        doubles: 31,
        triples: 4,
        hr: 32,
        rbi: 95,
        bb: 44,
        k: 152,
        sb: 30,
        avg: '.267',
        obp: '.324',
        slg: '.474',
        ops: '.798',
      },
      {
        season: '2026',
        team_id: 136,
        team_name: 'Seattle Mariners',
        age: 25,
        games_played: 31,
        pa: 135,
        ab: 121,
        r: 14,
        h: 31,
        doubles: 6,
        triples: 0,
        hr: 2,
        rbi: 12,
        bb: 12,
        k: 30,
        sb: 3,
        avg: '.256',
        obp: '.333',
        slg: '.355',
        ops: '.688',
      },
    ],
  } as unknown as AthletePayload['career'],
  splits: {
    season: 2026,
    group: 'hitting',
    fetched_at: '2026-04-29T05:55:32Z',
    cache_hit: true,
    home: {
      avg: '.273',
      obp: '.342',
      slg: '.364',
      ops: '.706',
      hr: 1,
      rbi: 6,
      ab: 66,
      h: 18,
    },
    away: {
      avg: '.236',
      obp: '.323',
      slg: '.345',
      ops: '.668',
      hr: 1,
      rbi: 6,
      ab: 55,
      h: 13,
    },
    vs_left: {
      avg: '.222',
      obp: '.344',
      slg: '.444',
      ops: '.788',
      hr: 2,
      rbi: 4,
      ab: 27,
      h: 6,
    },
    vs_right: {
      avg: '.266',
      obp: '.330',
      slg: '.330',
      ops: '.660',
      hr: 0,
      rbi: 8,
      ab: 94,
      h: 25,
    },
  } as unknown as AthletePayload['splits'],
  attended_summary: {
    games_attended: 34,
    games_with_box_score: 33,
    wins: 0,
    losses: 0,
    hitter: {
      pa: 137,
      ab: 130,
      r: 18,
      h: 33,
      doubles: 7,
      triples: 0,
      hr: 3,
      rbi: 16,
      bb: 6,
      k: 36,
      sb: 6,
      avg: '.254',
      obp: '.292',
      slg: '.377',
      ops: '.669',
    },
    pitcher: null,
  },
  attended_appearances: [
    {
      event_id: 104,
      event_date: '2026-04-11',
      title: 'Seattle Mariners vs Houston Astros',
      is_home: true,
      batting_line: {
        ab: 4,
        r: 1,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 1,
        hr: 1,
        doubles: 1,
        triples: 0,
        sb: 0,
        hbp: 0,
        pa: 4,
        total_bases: 6,
        left_on_base: 0,
        summary: '2-4 | HR, 2B, K',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: ['1 HR'],
    } as unknown as AthletePayload['attended_appearances'][number],
    {
      event_id: 55,
      event_date: '2025-09-24',
      title: 'Seattle Mariners vs Colorado Rockies',
      is_home: true,
      batting_line: {
        ab: 4,
        r: 1,
        h: 2,
        rbi: 1,
        bb: 1,
        k: 0,
        hr: 1,
        doubles: 0,
        triples: 0,
        sb: 0,
        hbp: 0,
        pa: 5,
        total_bases: 5,
        left_on_base: 1,
        summary: '2-4 | HR, BB, RBI',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: ['1 HR'],
    } as unknown as AthletePayload['attended_appearances'][number],
    {
      event_id: 94,
      event_date: '2025-09-14',
      title: 'Seattle Mariners vs Los Angeles Angels',
      is_home: true,
      batting_line: {
        ab: 3,
        r: 2,
        h: 2,
        rbi: 2,
        bb: 0,
        k: 0,
        hr: 0,
        doubles: 2,
        triples: 0,
        sb: 1,
        hbp: 0,
        pa: 3,
        total_bases: 4,
        left_on_base: 0,
        summary: '2-3 | 2 2B, 2 RBI, 2 R',
      },
      pitching_line: null,
      decision: null,
      notable: true,
      notable_reasons: [],
    } as unknown as AthletePayload['attended_appearances'][number],
  ],
  attended_appearance_count: 34,
};

const georgeKirby: AthletePayload = {
  player: {
    id: 4118,
    mlb_stats_id: 669923,
    full_name: 'George Kirby',
    primary_position: 'RHP',
    primary_number: '68',
    bats: 'R',
    throws: 'R',
    debut_date: '2022-05-08',
    birth_country: 'USA',
    photo_silo: null,
    photo_full: {
      cdn_url: 'https://cdn.rewind.rest/attending/player_full/4118',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#0c2c56',
      accent_color: '#c4ced4',
    },
    league: 'mlb',
    team: {
      id: 136,
      name: 'Seattle Mariners',
      abbreviation: 'SEA',
      league: 'mlb',
      primary_color: '#0c2c56',
      logo: {
        cdn_url: 'https://cdn.rewind.rest/attending/mlb_team_logo/136',
        url: null,
        thumbhash: null,
        dominant_color: '#0c2c56',
        accent_color: '#c4ced4',
      },
    },
  },
  supported: true,
  season_stats: {
    season: 2026,
    fetched_at: '2026-04-27T15:00:00Z',
    cache_hit: true,
    hitter: null,
    pitcher: {
      games_played: 5,
      games_started: 5,
      ip: '32.0',
      bf: 124,
      h: 28,
      r: 9,
      er: 9,
      bb: 6,
      k: 31,
      hr: 3,
      era: '2.53',
      whip: '1.06',
      decisions: { w: 3, l: 1, sv: 0, hld: 0, bs: 0 },
    },
  },
  attended_summary: {
    games_attended: 10,
    games_with_box_score: 10,
    wins: 6,
    losses: 4,
    hitter: null,
    pitcher: {
      ip: '65.1',
      bf: 238,
      h: 50,
      r: 26,
      er: 24,
      bb: 12,
      k: 71,
      era: '3.31',
      whip: '1.10',
      decisions: { w: 4, l: 3, sv: 0, hld: 0, bs: 0 },
      games_played: 10,
    },
  },
  attended_appearances: [
    {
      event_id: 9101,
      event_date: '2026-04-19T19:10:00Z',
      title: 'SEA vs ATL',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '7.0', h: 4, er: 1, bb: 1, k: 9 },
      decision: 'W',
      notable: true,
      notable_reasons: ['win'],
    },
    {
      event_id: 9102,
      event_date: '2026-04-04T19:10:00Z',
      title: 'SEA vs OAK',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '6.1', h: 7, er: 3, bb: 2, k: 7 },
      decision: 'L',
      notable: false,
      notable_reasons: [],
    },
    {
      event_id: 9103,
      event_date: '2025-09-21T19:10:00Z',
      title: 'SEA vs LAA',
      is_home: true,
      batting_line: null,
      pitching_line: { ip: '8.0', h: 3, er: 0, bb: 0, k: 11 },
      decision: 'W',
      notable: true,
      notable_reasons: ['win', '11 K'],
    },
  ],
  attended_appearance_count: 10,
};

const nflPlayerUnsupported: AthletePayload = {
  player: {
    id: 5500,
    mlb_stats_id: null,
    full_name: 'D.K. Metcalf',
    primary_position: 'WR',
    primary_number: '14',
    bats: null,
    throws: null,
    debut_date: null,
    birth_country: 'USA',
    photo_silo: null,
    photo_full: null,
    league: 'nfl',
    team: null,
  },
  supported: false,
  season_stats: null,
  attended_summary: {
    games_attended: 4,
    games_with_box_score: 0,
    wins: 2,
    losses: 2,
    hitter: null,
    pitcher: null,
  },
  attended_appearances: [
    {
      event_id: 9201,
      event_date: '2026-01-05T21:30:00Z',
      title: 'SEA at NYJ',
      is_home: false,
      batting_line: null,
      pitching_line: null,
      decision: null,
      notable: false,
      notable_reasons: [],
    },
    {
      event_id: 9202,
      event_date: '2025-12-15T21:25:00Z',
      title: 'SEA vs GB',
      is_home: true,
      batting_line: null,
      pitching_line: null,
      decision: null,
      notable: false,
      notable_reasons: [],
    },
  ],
  attended_appearance_count: 4,
};

export const fixtures: Record<string, AthletePayload> = {
  default: real,
  'jp-crawford': jpCrawford,
  'julio-rodriguez': julioRodriguez,
  pitcher: georgeKirby,
  'unsupported-nfl': nflPlayerUnsupported,
};
