import type { TopTracksPayload } from './components/TopTracksGrid.js';

const oliviaSample: TopTracksPayload['data'] = [
  {
    rank: 1,
    id: 9001,
    name: 'drivers license',
    detail: 'Olivia Rodrigo',
    album_id: 4101,
    album_name: 'SOUR',
    playcount: 58,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4101',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#cebeb0',
      accent_color: '#5d2638',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/drivers+license',
    apple_music_url:
      'https://music.apple.com/us/album/drivers-license/1546282209?i=1546282211',
    preview_url: null,
  },
  {
    rank: 2,
    id: 9002,
    name: 'good 4 u',
    detail: 'Olivia Rodrigo',
    album_id: 4101,
    album_name: 'SOUR',
    playcount: 41,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4101',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#cebeb0',
      accent_color: '#5d2638',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/good+4+u',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 3,
    id: 9003,
    name: 'vampire',
    detail: 'Olivia Rodrigo',
    album_id: 4102,
    album_name: 'GUTS',
    playcount: 36,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4102',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#7f1d4a',
      accent_color: '#f5b3c8',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/vampire',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 4,
    id: 9004,
    name: 'bad idea right?',
    detail: 'Olivia Rodrigo',
    album_id: 4102,
    album_name: 'GUTS',
    playcount: 30,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4102',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#7f1d4a',
      accent_color: '#f5b3c8',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/bad+idea+right',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 5,
    id: 9005,
    name: 'deja vu',
    detail: 'Olivia Rodrigo',
    album_id: 4101,
    album_name: 'SOUR',
    playcount: 27,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4101',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#cebeb0',
      accent_color: '#5d2638',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/deja+vu',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 6,
    id: 9006,
    name: 'happier',
    detail: 'Olivia Rodrigo',
    album_id: 4101,
    album_name: 'SOUR',
    playcount: 22,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4101',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#cebeb0',
      accent_color: '#5d2638',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/happier',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 7,
    id: 9007,
    name: 'all-american bitch',
    detail: 'Olivia Rodrigo',
    album_id: 4102,
    album_name: 'GUTS',
    playcount: 18,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4102',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#7f1d4a',
      accent_color: '#f5b3c8',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/all-american+bitch',
    apple_music_url: null,
    preview_url: null,
  },
  {
    rank: 8,
    id: 9008,
    name: 'jealousy, jealousy',
    detail: 'Olivia Rodrigo',
    album_id: 4101,
    album_name: 'SOUR',
    playcount: 14,
    image: {
      cdn_url: 'https://cdn.rewind.rest/listening/albums/4101',
      url: null,
      thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
      dominant_color: '#cebeb0',
      accent_color: '#5d2638',
    },
    url: 'https://www.last.fm/music/Olivia+Rodrigo/_/jealousy',
    apple_music_url: null,
    preview_url: null,
  },
];

const oliviaArtistFiltered: TopTracksPayload = {
  period: 'overall',
  artist_id: 1042,
  data: oliviaSample,
};

const oliviaArtistFilteredOneMonth: TopTracksPayload = {
  period: '1month',
  artist_id: 1042,
  data: oliviaSample.slice(0, 5),
};

const unfilteredAcrossArtists: TopTracksPayload = {
  period: '1month',
  artist_id: null,
  data: [
    {
      ...oliviaSample[2],
      rank: 1,
      detail: 'Olivia Rodrigo',
    },
    {
      rank: 2,
      id: 8200,
      name: 'Espresso',
      detail: 'Sabrina Carpenter',
      album_id: 5500,
      album_name: 'Short n’ Sweet',
      playcount: 32,
      image: {
        cdn_url: 'https://cdn.rewind.rest/listening/albums/5500',
        url: null,
        thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
        dominant_color: '#7a3a14',
        accent_color: '#f5d8a8',
      },
      url: 'https://www.last.fm/music/Sabrina+Carpenter/_/Espresso',
      apple_music_url: null,
      preview_url: null,
    },
    {
      rank: 3,
      id: 8400,
      name: 'Anti-Hero',
      detail: 'Taylor Swift',
      album_id: 5800,
      album_name: 'Midnights',
      playcount: 28,
      image: {
        cdn_url: 'https://cdn.rewind.rest/listening/albums/5800',
        url: null,
        thumbhash: 'KBgKDYJ4eHmXhoeEd4eIeIB4d3iIA4eHd4iIeIeIA4eHeId4iH',
        dominant_color: '#1c2030',
        accent_color: '#9c8a78',
      },
      url: 'https://www.last.fm/music/Taylor+Swift/_/Anti-Hero',
      apple_music_url: null,
      preview_url: null,
    },
    {
      rank: 4,
      id: 8500,
      name: 'Solar Power',
      detail: 'Lorde',
      album_id: 5900,
      album_name: 'Solar Power',
      playcount: 22,
      image: null,
      url: 'https://www.last.fm/music/Lorde/_/Solar+Power',
      apple_music_url: null,
      preview_url: null,
    },
  ],
};

export const fixtures: Record<string, TopTracksPayload> = {
  default: oliviaArtistFiltered,
  '1month': oliviaArtistFilteredOneMonth,
  unfiltered: unfilteredAcrossArtists,
};
